apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: parthmodi4659/test1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
      imagePullSecrets:
      - name: dockersecret